# Generated by Django 5.0.1 on 2024-02-27 22:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
        ('verbs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('verbs', models.ManyToManyField(related_name='defaut_tables', to='verbs.verb')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TableVerb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('done', models.BooleanField(default=False)),
                ('success', models.BooleanField(default=False)),
                ('verb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='verbs.verb')),
            ],
        ),
        migrations.CreateModel(
            name='UserTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_tables', to='profiles.profile')),
                ('verbs', models.ManyToManyField(related_name='user_tables', through='tables.TableVerb', to='verbs.verb')),
            ],
        ),
        migrations.AddField(
            model_name='tableverb',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.usertable'),
        ),
        migrations.AddConstraint(
            model_name='usertable',
            constraint=models.UniqueConstraint(fields=('name', 'profile'), name='unique table name'),
        ),
    ]
