# Generated by Django 5.0.1 on 2024-06-21 13:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Similarity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Verb',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('infinitive', models.CharField(blank=True, max_length=70)),
                ('simple_past', models.CharField(blank=True, max_length=70)),
                ('past_participle', models.CharField(blank=True, max_length=70)),
                ('translation', models.CharField(blank=True, max_length=70)),
                ('similarity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='verbs', to='verbs.similarity')),
            ],
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=255)),
                ('verb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='info', to='verbs.verb')),
            ],
        ),
        migrations.CreateModel(
            name='Example',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english', models.CharField(max_length=255)),
                ('translation', models.CharField(max_length=255)),
                ('verb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examples', to='verbs.verb')),
            ],
        ),
    ]
