# Generated by Django 5.0.1 on 2024-02-15 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Verb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('infinitive', models.CharField(blank=True, max_length=50)),
                ('simple_past', models.CharField(blank=True, max_length=50)),
                ('past_participle', models.CharField(blank=True, max_length=50)),
                ('translation', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
