# Generated by Django 5.1.1 on 2024-12-01 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Similarity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Similarities',
            },
        ),
        migrations.CreateModel(
            name='Verb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('infinitive', models.CharField(max_length=70)),
                ('simple_past', models.CharField(max_length=70)),
                ('past_participle', models.CharField(max_length=70)),
                ('translation', models.CharField(max_length=70)),
                ('similarity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='verbs', to='verbs.similarity')),
            ],
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=255)),
                ('verb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='info', to='verbs.verb')),
            ],
        ),
        migrations.CreateModel(
            name='Example',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english', models.CharField(max_length=255)),
                ('translation', models.CharField(max_length=255)),
                ('verb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examples', to='verbs.verb')),
            ],
        ),
    ]
