# Generated by Django 5.0.1 on 2024-02-15 09:06

import json
from django.db import migrations


def load_initial_verbs_data(apps, schema_editror):
    Verb = apps.get_model('verbs', 'Verb')
    with open('data/all_verbs.json', 'rb') as file:
        verbs_data = json.load(file)
    for verb_data in verbs_data:
        verb = Verb(
            infinitive=verb_data['infinitive'],
            simple_past=verb_data['simple_past'],
            past_participle=verb_data['past_participle'],
            translation=verb_data['translation']
        )
        verb.save()


class Migration(migrations.Migration):

    dependencies = [
        ('verbs', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_initial_verbs_data),
    ]
