# Generated by Django 5.0.1 on 2024-02-07 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='updated',
            new_name='last_update',
        ),
    ]
